# Generated by Django 4.2.7 on 2023-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='job_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
